### ISSUE TITLE
[DOCUMENTATION] Show example usage of gradle plugin

### ISSUE THREAD

**Issue by Zomis** [ASSERT-KTH/depclean#163]
(This didn't match either BUG or FEATURE)

I find this project interesting, and you have an example for how to use the Maven plugin, but I would like to use the Gradle plugin, but I'm missing instructions for that. I also think it would help bring more attention to this project if you clearly stated in your README that you support both Maven and Gradle.

Please provide an example for how to use depclean in a Gradle project.

**Comment by Zomis** [comment]
@monperrus Then what is this? https://github.com/ASSERT-KTH/depclean/tree/master/depclean-gradle-plugin
If it's not a Gradle plugin, then maybe consider removing it? Or at least write a README.md about what it is.

**Comment by monperrus** [comment]
You're right, there is a prototype of Gradle plugin that you can build from scratch (not deployed anywhere).

**Comment by cesarsotovalero** [comment]
Hi, there is a `README` here https://github.com/ASSERT-KTH/depclean/blob/master/depclean-gradle-plugin/README.md

**Comment by Zomis** [comment]
Thanks for adding that README, @cesarsotovalero !
