### ISSUE TITLE
[QUESTION] What are the differences between the minifaction done by depclean and maven-shade-plugin?

### ISSUE THREAD

**Issue by algomaster99** [ASSERT-KTH/depclean#165]
Hi!

I often disseminate this tool to people, so I aim to have as much knowledge as possible to answer their questions. Hence, I was wondering what 'extra' depclean does to remove bloated dependencies? Based on the documentation of [maven-shade-plugin](https://maven.apache.org/plugins/maven-shade-plugin/shade-mojo.html#createDependencyReducedPom), it seems that they also minify the JAR and call the new JAR as 'uber JAR'. Could you comment about the techniques used for debloating in both tools? I looked for keyword `shade` in your manuscript [here](https://arxiv.org/pdf/2001.07808.pdf), but I could not find it.

**Comment by monperrus** [comment]
ping @cesarsotovalero

**Comment by tdurieux** [comment]
the static analysis to detect the required dependencies is slightly different and Depclean aims to update the original pom.xml to exclude the unneeded dependencies instead of doing a post-processing.

**Comment by algomaster99** [comment]
[The Used, the Bloated, and the Vulnerable: Reducing the Attack Surface of an Industrial Application](https://ieeexplore.ieee.org/abstract/document/9609157) compares Depclean, Shade, and ProGuard. Based on results (table 2), Depclean debloats the jar to more degree and the tests pass - correctness guaranteed.

It is a small study on one project by SAP, but it is good to know :)
