### ISSUE TITLE
[BUG] ignoreDependencies doesn't work

### ISSUE THREAD

**Issue by davidkubecka-ext43694** [ASSERT-KTH/depclean#225]
**Describe the bug**
I'm trying to filter out spring boot starter dependencies from the analysis via 
```
mvn se.kth.castor:depclean-maven-plugin:2.0.6:depclean -DignoreDependencies="org.springframework.boot:.*"
```

However, I still the deps in the `POTENTIALLY UNUSED DIRECT DEPENDENCIES` section, e.g.
```
	org.springframework.boot:spring-boot-starter-actuator:2.7.5:compile (4 KB)
	org.springframework.boot:spring-boot-starter-web:2.7.5:compile (4 KB)
	org.springframework.boot:spring-boot-starter-test:2.7.5:test (4 KB)
```
OTOH, there's a note at the end of the analysis
```
Dependencies ignored in the analysis by the user [1]:
	org.springframework.boot:spring-boot-starter-data-redis:2.7.5:test
```
So it seems that the option is doing something.

**To Reproduce**
- create a pom with at least two `org.springframework.boot` dependencies
- run `mvn se.kth.castor:depclean-maven-plugin:2.0.6:depclean -DignoreDependencies="org.springframework.boot:.*"`

**Expected behavior**
No `org.springframework.boot` deps appear among the `POTENTIALLY UNUSED DIRECT DEPENDENCIES`.

**Comment by cesarsotovalero** [comment]
Hi @davidkubecka-ext43694, thanks for reporting this bug. It should be fixed in #248. Note that the dependencies matching `ignoredDependencies` will be treated as used by DepClean.
